### ISSUE TITLE
Extensibility question

### ISSUE THREAD

**Issue by glensc** [thephpleague/commonmark-ext-autolink#9]
So, if I want to do some customizations on the `@`-auto-linking. Should I just copy the class, as it's declared final and the logic inside is not very complex?

started something here:
- https://github.com/eventum/eventum/pull/507

but really I want to do some internal lookup of the match, skip expanding if lookup not found, and on match add `title` html attribute. And don't actually want to link the handle, because there's yet no user page in that application.

**Comment by colinodell** [comment]
> Should I just copy the class, as it's declared final and the logic inside is not very complex?

Correct.  This class only implements `InlineParserInterface` - it does not provide any other methods your subclass would benefit from, which is why we marked it as `final`.  See https://ocramius.github.io/blog/when-to-declare-classes-final/ for some thoughts on why `final` is a good choice in this situation

**Comment by glensc** [comment]
I mean how do I add extra functionality (like the example given)? I must fork the project? Or there are other means to achieve extensibility? post process of the node tree? add EventDispatcher and hook to events?

**Comment by colinodell** [comment]
You don't need to fork the whole project - just create your own version of this class implementing that same interface (copypaste it if you wish) and add it to the `Environment`.  Even if you _could_ extend that class there's really no reason why that would be beneficial, since you'd be copypasting 95% of the code anyway.
